language: cpp
compiler:
  - gcc
before_install:
  - git submodule update --init --recursive
  - echo 'yes' | sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
  - sudo apt-get update
  - sudo apt-get install gcc-4.8 g++-4.8
  - sudo ln -s -f gcc-4.8 /usr/bin/gcc
  - sudo ln -s -f g++-4.8 /usr/bin/g++
script: make linux
branches:
  only:
    - master
notifications:
  recipients:
    - newkedison@gmail.com
  email:
    on_success: change
    on_failure: always
