language: cpp
compiler:
  - gcc
before_install:
  - git submodule update --init --recursive
  - echo 'yes' | sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
  - sudo apt-get update
  - sudo apt-get install gcc-4.8 g++-4.8
  - sudo ln -s -f gcc-4.8 /usr/bin/gcc
  - sudo ln -s -f g++-4.8 /usr/bin/g++
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
  - sudo apt-get update
  - sudo apt-get install mongodb-10gen
  - sudo service mongodb start
  - sudo apt-get install valgrind
  - uname -a
  - gcc --version
  - ld --version
script: make linux && ./run_test.sh
branches:
  only:
    - master
notifications:
  recipients:
    - newkedison@gmail.com
  email:
    on_success: change
    on_failure: always
