language: cpp
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init --recursive
script: make linux
branches:
  only:
    - master
notifications:
  recipients:
    - newkedison@gmail.com
  email:
    on_success: change
    on_failure: always
